version: '3'

services:
  node-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: node-app
    environment:
      - DB_ADAPTER=${DB_ADAPTER}
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
